name: "End to end testing"
description: "Set up profile and run dbt with test project"
inputs:
  dbt_target:
    description: "Name of target to use when running dbt"
    required: true
    default: postgres


runs:
  using: "composite"
  steps:

    - name: Install python dependencies
      shell: bash
      run: |
        pip install --user --upgrade pip
        pip --version
        pip install -r dev-requirements.txt        

    - name: Run pytest
      shell: bash
      run: |
        echo ${{ inputs.dbt_target }}
        python3 -m pytest -c /.github/actions/end-to-end-test/ci.env

